from setuptools import setup, find_packages

setup(
    name="python_offline",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "psycopg2-binary>=2.9.10",
        "SQLAlchemy>=2.0.39",
        "pandas>=2.2.0",
        "numpy>=1.26.4",
        "polars>=0.20.7",
        "pyspark>=3.5.1",
        "pyarrow>=14.0.1",
        "findspark>=2.0.1",
        "pandera>=0.18.0",
        "great-expectations>=0.18.9",
        "matplotlib>=3.8.3",
        "seaborn>=0.13.2",
        "plotly>=5.18.0",
        "python-Levenshtein>=0.23.0",
        "pip-tools>=7.4.0",
        "jupyter>=1.0.0",
        "notebook>=7.0.7",
        "ipykernel>=6.29.0",
        "nbformat>=5.9.2",
        "nbconvert>=7.16.0",
        "tqdm>=4.66.2",
        "scikit-learn>=1.4.0",
        "graphviz>=0.20.1"
    ],
    author="Yavin Owens",
    author_email="your.email@example.com",
    description="A package for data engineering and analytics with validation",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/YavinOwens/Python_offline",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.10",
) 